apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Namespace is set dynamically via kubectl -n flag

labels:
- pairs:
    environment: production
    app.kubernetes.io/instance: production

patches:
  - target:
      kind: StatefulSet
      name: redis
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: "10Gi"

configMapGenerator:
  - name: redis-config
    files:
      - redis.conf

# In production, the secret must be created externally
# secretGenerator:
#   - name: redis-secret
#     behavior: replace
#     literals:
#       - password=<production-password>