apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - statefulset.yaml

labels:
- pairs:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: mes-infrastructure
    app.kubernetes.io/component: cache
    app.kubernetes.io/managed-by: kustomize