apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis
type: Opaque
data:
  # Default password: redis_password
  # This should be overridden in production
  password: cmVkaXNfcGFzc3dvcmQ=