apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: mes-infrastructure
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: mes-infrastructure
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis