apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: mes-localdev

labels:
- pairs:
    environment: localdev
    app.kubernetes.io/instance: localdev

patches:
  - target:
      kind: StatefulSet
      name: redis
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: REDIS_REPLICATION_MODE
          value: "master"

configMapGenerator:
  - name: redis-config
    files:
      - redis.conf

secretGenerator:
  - name: redis-secret
    literals:
      - password=local_redis_password