apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: mes-development

labels:
- pairs:
    environment: development
    app.kubernetes.io/instance: development

patches:
  - target:
      kind: StatefulSet
      name: redis
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: REDIS_REPLICATION_MODE
          value: "master"

configMapGenerator:
  - name: redis-config
    files:
      - redis.conf

# In development, the secret should be created externally by the pipeline
# secretGenerator:
#   - name: redis-secret
#     behavior: replace
#     literals:
#       - password=<development-password>